name: pipeline
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.12
  - r-base=4.3.1

  # Build tools
  - cmake
  - make
  - gcc
  - gxx

  # SAIGE / C++ dependencies
  - savvy
  - boost
  - openblas
  - zlib
  - libcurl
  - libxml2
  - openssl
  - superlu
  - libdeflate

  # R dependencies
  - r-matrix
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppeigen
  - r-data.table
  - r-bh
  - r-rsqlite
  - r-devtools
  - r-optparse
  - r-skat
  - r-spatest
  - r-rcppparallel

   # PLINK 2.0
  - plink2

  - pip
  - pip:
      - cget
      - click
